package sys.model;
// Generated 9/08/2019 09:14:19 AM by Hibernate Tools 4.3.1



/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private short idEstudiante;
     private String nombre;
     private String apellido;

    public Estudiantes() {
    }

	
    public Estudiantes(short idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public Estudiantes(short idEstudiante, String nombre, String apellido) {
       this.idEstudiante = idEstudiante;
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
    public short getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(short idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


